image: docker:24.0.6
services:
  - docker:24.0.6-dind

variables:
  DOCKER_DRIVER: overlay
  CACHE_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
 
stages:
  - build
  - deploy

docker-build:
  stage: build
  script:
    - apk add --no-cache curl
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CACHE_IMAGE:build-vue || true
    - docker pull $CACHE_IMAGE:production || true
    - docker build
        --target build-vue
        --cache-from $CACHE_IMAGE:build-vue
        --tag $CACHE_IMAGE:build-vue
        --file ./Dockerfile
        "."
    - docker build
        --cache-from $CACHE_IMAGE:production
        --tag $CACHE_IMAGE:production
        --file ./Dockerfile
        "."
    - docker push $CACHE_IMAGE:build-vue
    - docker push $CACHE_IMAGE:production
    - chmod +x ./release.sh
    - ./release.sh

deploy-staging:
  stage: deploy
  script:
    - eb use covid-watch-dev -v
    - eb deploy covid-watch-dev -v
  environment:
    name: covid-watch-dev
  only:
    - develop