image: docker:stable
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  CI_REGISTRY: registry.gitlab.com
  CI_PROJECT_NAMESPACE: devpatrol1
  CI_PROJECT_NAME: covid-watch-project
  CI_REGISTRY_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
  APP_ENV_NAME: covid-watch-dev
  APP_NAME: covid-watch
  DOCKER_TLS_CERTDIR: ""
 
stages:
  - build
  - deploy

docker-build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

deploy-image:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  before_script:
    - aws --version
  script:
    - export DEPLOY_TOKEN=$(echo $GITLAB_REGISTRY_TOKEN | tr -d "\n" | base64)
    - aws s3 cp config.json s3://$S3_BUCKET_NAME/config.json
    - aws s3 cp Dockerrun.aws.json s3://$S3_BUCKET_NAME/Dockerrun.aws.json
    - aws elasticbeanstalk create-application-version --application-name $APP_NAME --version-label $CI_PIPELINE_IID --source-bundle S3Bucket=$S3_BUCKET_NAME,S3Key=Dockerrun.aws.json
    - aws elasticbeanstalk update-environment --application-name $APP_NAME --environment-name $APP_ENV_NAME --version-label=$CI_PIPELINE_IID