# fly.toml app configuration file generated for covid-watch on 2023-10-09T18:28:02-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "covid-watch"
primary_region = "sjc"


[build]
  image = "patrol007/covid-watch:latest"


[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
